<?php

return [
    'about' => 'Haqqımızda',
    'add_course' => 'Yeni kurs',
    'blogs' => 'Bloqlar',
    'contact' => 'Əlaqə',
    'copyright' => '"Digiuth” layihəsi “Erasmus Tələbə Şəbəkəsi – Azərbaycan” ictimai birliyi tərəfindən icra olunur.',
    'courses' => 'Kurslar',
    'events' => 'Tədbirlər',
    'hi' => 'Xoş gördük',
    'home' => 'Ana səhifə',
    'language' => 'Dil',
    'login' => 'Giriş',
    'logout' => 'Çıxış',
    'materials' => 'Yeniliklər',
    'my_courses' => 'Kurslarım',
    'news' => 'Xəbərlər',
    'our_partners' => 'Tərəfdaşlarımız',
    'our_team' => 'Komandamız',
    'personal_cabinet' => 'Şəxsi Kabinet',
    'registerAsStudent' => 'İstifadəçi kimi qeydiyyat',
    'registerAsTeacher' => 'Təlimçi kimi qeydiyyat',
    'registerAsMentor' => 'Mentor kimi qeydiyyat',
    'search' => 'Axtar',
    'services' => 'Saytın xəritəsi',
    'slogan' => 'Digiuth ekspertlərin hazırladığı onlayn kurslar vasitəsilə gənclərin biznes, texnologiya və yaradıcılıq bacarıqlarını kəşf etməyə və inkişaf etdirməyə kömək edən onlayn təhsil platformasıdır.',
    'supported' => 'Dəstək:',
    'trainers' => 'Təlimçilərimiz',
    'mentors' => 'Mentorlarımız',
    'update_profile' => 'Profili yeniləyin'
];
