<?php

return [
    'The expected event was not found' => 'Nəzərdə tutulan tədbir yoxdur.',
    'Your email' => 'Sizin Elektron poçtunuz',
    'about_course' => 'Kurs haqqında',
    'all' => 'Hamısı',
    'already_joined' => 'Siz artıq qoşulmusunuz.',
    'categories' => 'Kateqoriyalar',
    'certificate_body' => '"Digiuth" onlayn platformasında kursu müvəffəqiyyətlə başa vurduğu üçün',
    'certificate_presenting' => 'Sertifikat verilir',
    'copyright' => 'Copyright © 2022 ESN Azerbaijan',
    'correct_question_count' => 'Düzgün sual sayı',
    'course_comment_title' => 'Rəylər',
    'course_content' => 'Kurs məzmunu',
    'course_duration' => 'Kurs müddəti',
    'course_language' => 'Kursun dili',
    'course_name' => 'Kurs adı',
    'cv' => 'CV',
    'date' => 'Tarix',
    'do-comment' => 'Rəy yaz',
    'email' => 'Elektron poçt',
    'email_or_username' => 'Elektron poçt və ya istifadəçi adı',
    'event_feature' => 'Tədbirin detalları',
    'exam' => 'Imtahan',
    'follow_us' => 'Bizi izlə',
    'forgot_password' => 'Parolu unutdum',
    'forgot_password_msg' => 'Parolumu unutdum',
    'forgot_success_message' => 'Parolu sıfırlamaq üçün email göndərildi',
    'fullname' => 'Tam Adınız',
    'general_info' => 'Ümumi məlumat',
    'join' => 'Qoşul',
    'lecture_count' => 'Dərs sayı',
    'my_certificates' => 'Mənim sertifikatlarım',
    'operations' => 'Əməliyyatlar',
    'or' => 'və ya',
    'organizer' => 'Təşkilatçı',
    'our_events' => 'Bizim tədbirlərimiz',
    'password' => 'parol',
    'phone' => 'Telefon',
    'photo' => 'Şəkil',
    'place' => 'Yer',
    'position' => 'Mövqe',
    'register_as_student' => 'Tələbə kimi qeydiyyatdan keç',
    'register_as_teacher' => 'Təlimçi kimi qeydiyyatdan keç',
    'register_as_mentor' => 'Mentor kimi qeydiyyatdan keç',

    'releated_post' => 'Əlaqəli post',
    'repassword' => 'parolu yenidən qeyd edin',
    'reset_password_msg' => 'Parolu sıfırla',
    'reset_success_message' => 'Parolunuz sıfırlandı',
    'section_count' => 'Fəsil sayı',
    'signup' => 'Daxil Ol',
    'start_date' => 'Başlanğıc tarixi',
    'submit' => 'Qeydiyyatdan keç',
    'time' => 'Vaxt',
    'total_question_count' => 'Ümumi sual sayı',
    'trainer_name' => 'Təlimçinin adı',
    'upcoming_events' => 'Gözlənilən tədbirlər',
    'upload' => 'Yüklə',
    'username' => 'İstifadəçi adı',
    'website' => 'Veb-səhifə',
    'your_email' => 'Sizin Elektron poçtunuz',
    'your_rate' => 'Sizin dəyərləndirməniz',
    'password_error_t' => "Şifrə ən azı 8, ən çox 32 simvol olmalıdır.
    Şifrədə bir böyük hərf (A-Z) olmalıdır.
    Şifrədə bir kiçik hərf (a-z) olmalıdır.
    Şifrədə ən azı bir xüsusi simvol olmalıdır: ~ ! @ # $ % ^ * ( ) _ - + = { } [ ] | : ; " . " , ? . < > & və ya ' işarələrindən istifadə edilməməlidir.
    Şifrədə bir rəqəm (0-9) olmalıdır.",
    'register' => 'Qeydiyyat',

    'mentor' => 'Mentor',
    'teacher' => 'Təlimçi',
    'student' => 'İstifadəçi',
    'your_password' => 'Şifrəniz',
    'enter_your_password_again' => 'Şifrəsinizi yenidən daxil edin',
    'linkedin_link' => 'Linkedin hesabınız',
    'facebook_link' => 'Facebook hesabınız',
    'instagram_link' => 'İnstagram hesabınız',
    'send-message' => 'Mesaj göndər',
    'send' => 'Göndər',
    'close' => 'Bağla',
    'other' => 'Digər',
    'my_cabinet' => 'Kabinetim',
    'name' => 'Ad',
    'surname' => 'Soyad',
    'user' => 'İstifadəçi',
    'user_not_found' => 'Istifadəçi tapılmadı!'
];
