<?php

return [
    'about' => 'About us',
    'add_course' => 'Add course',
    'blogs' => 'Blogs',
    'certificates' => 'My certificates',
    'contact' => 'Contact',
    'copyright' => 'The Digiuth project is coordinated by Erasmus Student Network Azerbaijan',
    'courses' => 'Courses',
    'events' => 'Events',
    'exam' => 'İmtahan',
    'hi' => 'Hi',
    'home' => 'Home',
    'language' => 'Lang',
    'login' => 'Login',
    'logout' => 'Logout',
    'materials' => 'What is new?',
    'my_courses' => 'My courses',
    'news' => 'News',
    'our_partners' => 'Our partners',
    'our_team' => 'Our team',
    'personal_cabinet' => 'Personal Cabinet',
    'registerAsStudent' => 'Register as student',
    'registerAsTeacher' => 'Register as trainer',
    'registerAsMentor' => 'Register as mentor',
    'search' => 'Search',
    'services' => 'Map of the Website',
    'slogan' => 'Digiuth is an online educational platform that helps you discover and develop business, technology-related, and creative skills through expert-led course videos.',
    'supported' => '.',
    'trainers' => 'Our trainers',
    'mentors' => 'Our mentors',
    'update_profile' => 'Update profile'
];
